#version 450
layout(local_size_x = 256) in;

/*
CLAMP:
out[i] = clamp(x[i], lo, hi)
*/

layout(std430, set=0, binding=0) readonly buffer X { float x[]; };
layout(std430, set=0, binding=1) writeonly buffer O { float outv[]; };

layout(push_constant) uniform PC {
  uint n;
  float lo;
  float hi;
} pc;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= pc.n) return;
  float v = x[i];
  outv[i] = clamp(v, pc.lo, pc.hi);
}
