#version 450
layout(local_size_x = 256) in;

/*
MUL: out[i] = a[i] * b[i]
*/

layout(std430, set=0, binding=0) readonly buffer A { float a[]; };
layout(std430, set=0, binding=1) readonly buffer B { float b[]; };
layout(std430, set=0, binding=2) writeonly buffer O { float outv[]; };

layout(push_constant) uniform PC { uint n; } pc;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= pc.n) return;
  outv[i] = a[i] * b[i];
}
