#version 450
layout(local_size_x = 256) in;

/*
SIGMOID:
out[i] = 1 / (1 + exp(-x[i]))
*/

layout(std430, set=0, binding=0) readonly buffer X { float x[]; };
layout(std430, set=0, binding=1) writeonly buffer O { float outv[]; };

layout(push_constant) uniform PC { uint n; } pc;

void main() {
  uint i = gl_GlobalInvocationID.x;
  if (i >= pc.n) return;

  float v = x[i];
  outv[i] = 1.0 / (1.0 + exp(-v));
}
