#version 450
layout(local_size_x = 1) in;

layout(std430, set=0, binding=0) readonly buffer SBC { uint SB_count[]; };
layout(std430, set=0, binding=1) writeonly buffer QSB { uint Q_SB_base[]; }; // [n_sb+1] in bits

layout(push_constant) uniform PC {
    uint n_sb;
} pc;

void main() {
    uint sum = 0u;
    Q_SB_base[0] = 0u;
    for (uint sb = 0u; sb < pc.n_sb; sb++) {
        sum += SB_count[sb];
        Q_SB_base[sb + 1u] = sum;
    }
}
